// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../packages/FsCheck.2.1.0/lib/net45/FsCheck.dll"
#r "../../packages/FsCheck.Xunit.2.1.0/lib/net45/FsCheck.Xunit.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "../../packages/xunit.runner.visualstudio.2.1.0/build/_common/xunit.abstractions.dll"
#r "../../packages/xunit.assert.2.1.0/lib/dotnet/xunit.assert.dll"
#r "../../packages/xunit.extensibility.core.2.1.0/lib/dotnet/xunit.core.dll"
#r "../../packages/xunit.extensibility.execution.2.1.0/lib/net45/xunit.execution.desktop.dll"
#r "../../packages/Unquote.3.1.0/lib/net45/Unquote.dll"
#r "../../packages/FSharp.Control.AsyncSeq.1.13/lib/net40/FSharp.Control.AsyncSeq.dll"
#r "../../packages/FSharpx.Async.1.12.0/lib/net40/FSharpx.Async.dll"
#r "../../packages/FSharpx.Collections.1.10.1/lib/net40/FSharpx.Collections.dll"
#r "../../packages/FSharpx.Extras.1.10.2/lib/40/FSharpx.Extras.dll"