// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "../../packages/FsCheck/lib/net45/FsCheck.dll"
#r "../../packages/FsCheck.Xunit/lib/net45/FsCheck.Xunit.dll"
#r "../../packages/FSharp.Control.AsyncSeq/lib/net45/FSharp.Control.AsyncSeq.dll"
#r "../../packages/FSharpx.Async/lib/net40/FSharpx.Async.dll"
#r "../../packages/FSharpx.Collections/lib/net40/FSharpx.Collections.dll"
#r "../../packages/FSharpx.Extras/lib/40/FSharpx.Extras.dll"
#r "../../packages/Unquote/lib/net45/Unquote.dll"
#r "../../packages/xunit.runner.visualstudio/build/_common/xunit.abstractions.dll"
#r "../../packages/xunit.assert/lib/portable-net45+win8+wp8+wpa81/xunit.assert.dll"
#r "../../packages/xunit.extensibility.core/lib/portable-net45+win8+wp8+wpa81/xunit.core.dll"
#r "../../packages/xunit.extensibility.execution/lib/net45/xunit.execution.desktop.dll"